### ISSUE TITLE
unregisterHandler in JS

### ISSUE THREAD

**Issue by igabesz** [marcuswestin/WebViewJavascriptBridge#234] opened 2016-09-20 09:17 UTC
We would like to use this app with dynamic subscriptions. Thus we need an `unregisterHandler` function, similar to `registerHandler`. Is this possible? 

For example: 

``` javascript
let handlerId = bridge.registerHandler('event-name', (data) => { /* ... */ })
bridge.unregisterHandler(handlerId);
```

**Comment by marcuswestin** [comment] 2016-12-13 18:28
Would accept a good pr

**Comment by marcuswestin** [comment] 2016-12-13 21:14
Also see #216

**Comment by marcuswestin** [comment] 2016-12-13 21:16
Dupe of #118

**Closed by marcuswestin** 2016-12-13 21:16 UTC
Labels: Feature Proposal, Up for grabs
