### ISSUE TITLE
about callhandle only Execute once

### ISSUE THREAD

**Issue by EasonGaoDevelop** [marcuswestin/WebViewJavascriptBridge#224] opened 2016-07-13 03:06 UTC
When I use WebViewJavascriptBridge found callback executes only once, debug found is the execution of the delete responseCallbacks[message.responseId] in WebViewJavascriptBridge.js.text I can delete this line of code?

**Comment by zawaliang** [comment] 2016-08-08 01:47
You can use "+ (instancetype)bridgeForWebView:(WVJB_WEBVIEW_TYPE*)webView webViewDelegate:(WVJB_WEBVIEW_DELEGATE_TYPE*)webViewDelegate handler:(WVJBHandler)messageHandler resourceBundle:(NSBundle*)bundle" method

**Comment by zawaliang** [comment] 2016-08-08 01:48
@EasonGaoDevelop You can use "+ (instancetype)bridgeForWebView:(WVJB_WEBVIEW_TYPE)webView webViewDelegate:(WVJB_WEBVIEW_DELEGATE_TYPE)webViewDelegate handler:(WVJBHandler)messageHandler resourceBundle:(NSBundle*)bundle" method

**Comment by marcuswestin** [comment] 2016-12-13 17:56
Dupe of #213

**Closed by marcuswestin** 2016-12-13 17:56 UTC
